// <auto-generated />
using System;
using Madyan.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace SampleApp.Migrations
{
    [DbContext(typeof(DDBDBContext))]
    [Migration("20190401092511_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.3-servicing-35854")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Madyan.Data.Basic", b =>
                {
                    b.Property<long>("BasicID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DateOfBirth");

                    b.Property<long?>("FkPatientID");

                    b.Property<string>("Forenames");

                    b.Property<string>("HomeTelephoneNumber");

                    b.Property<string>("PasNumber");

                    b.Property<string>("SexCode");

                    b.Property<string>("Surname");

                    b.HasKey("BasicID");

                    b.HasIndex("FkPatientID")
                        .IsUnique()
                        .HasFilter("[FkPatientID] IS NOT NULL");

                    b.ToTable("Basic");
                });

            modelBuilder.Entity("Madyan.Data.GpDetail", b =>
                {
                    b.Property<long>("GpDetailID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long?>("FkPatientID");

                    b.Property<string>("GpCode");

                    b.Property<string>("GpInitials");

                    b.Property<string>("GpPhone");

                    b.Property<string>("GpSurname");

                    b.HasKey("GpDetailID");

                    b.HasIndex("FkPatientID");

                    b.ToTable("GpDetail");
                });

            modelBuilder.Entity("Madyan.Data.NextOfKin", b =>
                {
                    b.Property<long>("NextOfKinID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long?>("FkPatientID");

                    b.Property<string>("NokAddressLine1");

                    b.Property<string>("NokAddressLine2");

                    b.Property<string>("NokAddressLine3");

                    b.Property<string>("NokAddressLine4");

                    b.Property<string>("NokName");

                    b.Property<string>("NokPostcode");

                    b.Property<string>("NokRelationshipCode");

                    b.HasKey("NextOfKinID");

                    b.HasIndex("FkPatientID")
                        .IsUnique()
                        .HasFilter("[FkPatientID] IS NOT NULL");

                    b.ToTable("NextOfKin");
                });

            modelBuilder.Entity("Madyan.Data.Patient", b =>
                {
                    b.Property<long>("PatientID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.HasKey("PatientID");

                    b.ToTable("Patient");
                });

            modelBuilder.Entity("Madyan.Data.Basic", b =>
                {
                    b.HasOne("Madyan.Data.Patient", "FkPatient")
                        .WithOne("FkBasic")
                        .HasForeignKey("Madyan.Data.Basic", "FkPatientID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Madyan.Data.GpDetail", b =>
                {
                    b.HasOne("Madyan.Data.Patient", "FkPatient")
                        .WithMany("GpDetailList")
                        .HasForeignKey("FkPatientID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Madyan.Data.NextOfKin", b =>
                {
                    b.HasOne("Madyan.Data.Patient", "FkPatient")
                        .WithOne("FkNextOfKin")
                        .HasForeignKey("Madyan.Data.NextOfKin", "FkPatientID")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
