// <auto-generated />
using System;
using Madyan.Data.Exception;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace SampleApp.Migrations.ExceptionDB
{
    [DbContext(typeof(ExceptionDBContext))]
    [Migration("20190401092528_initExceptionDBContext")]
    partial class initExceptionDBContext
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.3-servicing-35854")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Madyan.Data.Exception.ErrorDetails", b =>
                {
                    b.Property<long>("ErrorID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("ErrorDate");

                    b.Property<string>("Message");

                    b.Property<int>("StatusCode");

                    b.HasKey("ErrorID");

                    b.ToTable("ErrorDetails");
                });
#pragma warning restore 612, 618
        }
    }
}
